spring.datasource.url=jdbc:mysql://root:GaHhZHsfhHilzQoSTHerWTqyKQOpKORc@altaria.proxy.rlwy.net:13662/railway
spring.datasource.username=root
spring.datasource.password=GaHhZHsfhHilzQoSTHerWTqyKQOpKORc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect